#!/usr/bin/env python3
"""Regenerates web/dragtables.js from the raw tables in tools/dragdata/.

Sources (see ALGORITHMS.md):
  mcg1/2/5/6/7/8/gi.txt, ra4.txt : CD vs Mach, JBM Ballistics downloads page
      (https://jbmballistics.com/downloads.html), obtained by JBM from the US Army
      Ballistic Research Laboratory (BRL).
  olin.txt : G1, G5, G6, GL retardation functions vs velocity (ft/s) from
      E. D. Lowry, "Exterior Ballistics of Small Arms Projectiles",
      Winchester-Western / Olin Mathieson, 1965 (as tabulated by JBM).

The GL table has no published CD-vs-Mach form, so it is derived here as
  CD_GL(M) = CD_G1(M) * GL(v) / G1(v)
using Lowry's own G1 and GL columns at the same velocity (both are expressed
on the same basis, so their ratio is the ratio of drag coefficients). Lowry
lists GL only to 3600 ft/s; above that the last ratio is held constant.
Velocity is converted to Mach with the ICAO sea-level speed of sound
(1116.45 ft/s) - Lowry's tables used 1120.27 ft/s (59 F); the difference moves
the GL break-point by 0.3 %, well inside the precision of the source table.
"""
import os, re, json
HERE = os.path.dirname(os.path.abspath(__file__))
D = os.path.join(HERE, "dragdata")

def read_cd(fname):
    pts = []
    for line in open(os.path.join(D, fname)):
        nums = re.findall(r"[-+]?\d*\.?\d+", line)
        if len(nums) >= 2:
            pts.append((float(nums[0]), float(nums[1])))
    return pts

tables = {
    "G1": read_cd("mcg1.txt"), "G2": read_cd("mcg2.txt"), "G5": read_cd("mcg5.txt"),
    "G6": read_cd("mcg6.txt"), "G7": read_cd("mcg7.txt"), "G8": read_cd("mcg8.txt"),
    "GI": read_cd("mcgi.txt"), "RA4": read_cd("ra4.txt"),
}

# Lowry / Olin G1 and GL columns
olin = []
for line in open(os.path.join(D, "olin.txt")):
    parts = line.replace("*", "").split()
    if len(parts) == 5 and parts[0].isdigit():
        olin.append((float(parts[0]), float(parts[1]), float(parts[4])))
def ratio_at(v_fps):
    if v_fps <= olin[0][0]:
        return olin[0][2] / olin[0][1]
    for (v0, g0, l0), (v1, g1, l1) in zip(olin, olin[1:]):
        if v_fps <= v1:
            f = (v_fps - v0) / (v1 - v0)
            return (l0 + f * (l1 - l0)) / (g0 + f * (g1 - g0))
    v, g, l = olin[-1]
    return l / g
C_FPS = 340.294 / 0.3048
tables["GL"] = [(m, round(cd * ratio_at(m * C_FPS), 4)) for m, cd in tables["G1"]]

order = ["G1", "G2", "G5", "G6", "G7", "G8", "GI", "GL", "RA4"]
out = ["// GENERATED by tools/make_drag_tables.py - do not edit by hand.",
       "// Standard drag functions: [Mach, CD] pairs. Sources: see ALGORITHMS.md.",
       "(function (root) {", "  'use strict';", "  var T = {};"]
for k in order:
    flat = ",".join("%g,%g" % p for p in tables[k])
    out.append("  T.%s = [%s];" % (k, flat))
out += ["  root.BallistoDragTables = T;",
        "  if (typeof module !== 'undefined' && module.exports) module.exports = T;",
        "})(typeof window !== 'undefined' ? window : globalThis);", ""]
open(os.path.join(HERE, "..", "web", "dragtables.js"), "w").write("\n".join(out))
for k in order:
    print(k, len(tables[k]), "points, Mach", tables[k][0][0], "-", tables[k][-1][0])
